'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class producto
    Public Property id As Integer
    Public Property producto1 As String
    Public Property descripcion As String
    Public Property estado As String
    Public Property precio As Nullable(Of Decimal)

End Class
